### PR TITLE
Use lerna

### PR DESCRIPTION
**Pull request by dan-muller**

### CODE REVIEW

**Comment by douglasnaphas** [comment]
[Note](https://github.com/lerna/lerna#what-cant-lerna-do):

> Lerna is not a deployment tool for serverless monorepos. Hoisting might be incompatible with traditional serverless monorepo deployment techniques.

I think our dependencies have to exist in multiple places because each Lambda's ZIP file needs a copy of the dependencies that Lerna would try to de-duplicate.

**Comment by dan-muller** [comment]
https://github.com/dan-muller/room-app/pull/10#issuecomment-888782431

I didnt see that, thats a shame, I though lerna looked pretty cool

**Comment by dan-muller** [comment]
There are a couple of (somewhat) recent examples:
https://github.com/danielblignaut/cdk-monorepo-example
https://github.com/jogold/cdk-lambda-nodejs-monorepo

I wonder if something has changed

**Comment by dan-muller** [comment]
Maybe they (lerna) meant [serverless](https://www.serverless.com/) serverless and not cdk serverless.

**Comment by douglasnaphas** [comment]
Lerna might still work, I haven't looked into it much beyond seeing that one note in the docs.

**Comment by dan-muller** [comment]
I just found a non-lerna example here
https://codeload.github.com/kpiteng/lerna/zip/refs/heads/main

**Comment by douglasnaphas** [comment]
I know the CDK itself uses Lerna.

**Comment by dan-muller** [comment]
image

@douglasnaphas what do you think is going on here?

**Comment by douglasnaphas** [comment]
> image
> 
> @douglasnaphas what do you think is going on here?

I bet the files are not present in the bucket. I think a 403 happens when you request a path or object name that isn’t there.

You can test that theory by doing a fetch from the browser for a non-existent path.

If there was some rearranging of where S3 objects wind up, I bet it’s related to that.

I’d take a look at the S3 bucket to see what its structure is like, and compare that to the paths of the chunks in the requests that failed.

If nothing about the S3 structure and path names seems awry, you could try a CloudFront cache invalidation, in case you’re somehow getting an old index.js that wants old chunks. However, I’ve never had that kind of problem with S3/CloudFront sites, so if that fixes it we’d need to understand what went wrong.

**Comment by dan-muller** [comment]
:test_tube:

**Comment by douglasnaphas** [comment]
With other create-react-app + CloudFront + S3 sites, I’ve needed [“homepage”: “.”](https://github.com/cdk-turnkey/brian-liberation/blob/6d59781556f0c72233d419759a03b13a50c48386/frontend/package.json#L6) in the front end `package.json` to allow the files to be found by the browser.

**Comment by dan-muller** [comment]
@douglasnaphas I'm struggling to find the right path for the lambdas, any ideas?

**Pull request closed without merging**
